# All distances expressed in metres unless otherwise stated
crs: "EPSG:26910"          # NAD83 / UTM zone 10N
rock_a: "is_ultramafic"
rock_b: "is_granodiorite"
falloff_km: 10.0           # Gaussian dₘ (in km)

# H3 grid parameters
grid:
  type: "h3"
  resolution: 7            # ≈ 2.6 km hexagon edge

# Output locations
paths:
  input_gpkg: "data/raw/BedrockP.gpkg"
  parquet: "data/processed/prospectivity.parquet"
  static_png: "data/processed/prospectivity.png"
  interactive_html: "data/processed/prospectivity.html"
